### ISSUE TITLE
Create relation 'blockers' to find who is blocking me

### ISSUE THREAD

**Issue by weiserma** [nejdetkadir/followability#9]
This should be the inverse of the blocks the same as following/followers are inverse of each other.

**Comment by weiserma** [comment]
perhaps you can add an info field so you can pass a reason for friendship or a block.   

- send_follow_request_to?(obj, reason='')
- block(obj, reason='')

I see value to use this data for 1) follow to decide to accept/reject and 2) admin can decide if the block reason should have further consequences.

**Comment by nejdetkadir** [comment]
> This should be the inverse of the blocks the same as following/followers are inverse of each other.

Hi @weiserma, I created an PR for creating blockers relation.

**Comment by nejdetkadir** [comment]
> perhaps you can add an info field so you can pass a reason for friendship or a block.
> 
> * send_follow_request_to?(obj, reason='')
> * block(obj, reason='')
> 
> I see value to use this data for 1) follow to decide to accept/reject and 2) admin can decide if the block reason should have further consequences.

Hey @weiserma, thanks for writing this up. I think this feature is beyond the scope of this gem. 

You can create an extension for this feature if you want. 👌🏻
